
package service.web.kaituo.org;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* LogService service = new LogService();
* LogServicePortType portType = service.getLogServiceHttpSoap11Endpoint();
* portType.query(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "LogService", targetNamespace = "http://service.web.kaituo.org", wsdlLocation = "http://10.35.50.231/axis2/services/LogService?wsdl")
public class LogService extends Service {

	private final static URL LOGSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(service.web.kaituo.org.LogService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = service.web.kaituo.org.LogService.class.getResource(".");
			url = new URL(baseUrl, "http://10.35.50.231/axis2/services/LogService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://10.35.50.231/axis2/services/LogService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		LOGSERVICE_WSDL_LOCATION = url;
	}

	public LogService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LogService() {
		super(LOGSERVICE_WSDL_LOCATION, new QName("http://service.web.kaituo.org", "LogService"));
	}

	/**
	 * 
	 * @return returns LogServicePortType
	 */
	@WebEndpoint(name = "LogServiceHttpSoap11Endpoint")
	public LogServicePortType getLogServiceHttpSoap11Endpoint() {
		return super.getPort(new QName("http://service.web.kaituo.org", "LogServiceHttpSoap11Endpoint"),
				LogServicePortType.class);
	}

	/**
	 * 
	 * @return returns LogServicePortType
	 */
	@WebEndpoint(name = "LogServiceHttpSoap12Endpoint")
	public LogServicePortType getLogServiceHttpSoap12Endpoint() {
		return super.getPort(new QName("http://service.web.kaituo.org", "LogServiceHttpSoap12Endpoint"),
				LogServicePortType.class);
	}

	/**
	 * 
	 * @return returns LogServicePortType
	 */
	@WebEndpoint(name = "LogServiceHttpEndpoint")
	public LogServicePortType getLogServiceHttpEndpoint() {
		return super.getPort(new QName("http://service.web.kaituo.org", "LogServiceHttpEndpoint"),
				LogServicePortType.class);
	}

}
