
package service.web.kaituo.org;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LogServicePortType", targetNamespace = "http://service.web.kaituo.org")
public interface LogServicePortType {

	/**
	 * 
	 * @param sendID
	 * @param regID
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:query")
	@WebResult(targetNamespace = "http://service.web.kaituo.org")
	@RequestWrapper(localName = "query", targetNamespace = "http://service.web.kaituo.org", className = "service.web.kaituo.org.Query")
	@ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.web.kaituo.org", className = "service.web.kaituo.org.QueryResponse")
	public String query(@WebParam(name = "RegID", targetNamespace = "http://service.web.kaituo.org") String regID,
			@WebParam(name = "SendID", targetNamespace = "http://service.web.kaituo.org") String sendID);

	/**
	 * 
	 * @param logType
	 * @param sendID
	 * @param regID
	 * @param logs
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:acceptLogs")
	@WebResult(targetNamespace = "http://service.web.kaituo.org")
	@RequestWrapper(localName = "acceptLogs", targetNamespace = "http://service.web.kaituo.org", className = "service.web.kaituo.org.AcceptLogs")
	@ResponseWrapper(localName = "acceptLogsResponse", targetNamespace = "http://service.web.kaituo.org", className = "service.web.kaituo.org.AcceptLogsResponse")
	public String acceptLogs(@WebParam(name = "RegID", targetNamespace = "http://service.web.kaituo.org") String regID,
			@WebParam(name = "SendID", targetNamespace = "http://service.web.kaituo.org") String sendID,
			@WebParam(name = "LogType", targetNamespace = "http://service.web.kaituo.org") String logType,
			@WebParam(name = "Logs", targetNamespace = "http://service.web.kaituo.org") String logs);

}
