#-------Oracle-------#
jdbc.driverClassName1=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@192.168.1.15:1521:JYGAJG
jdbc.url1=jdbc:oracle:thin:@50.64.129.48:1521:jygaxtbgtest
jdbc.username1=YWSZ
jdbc.password1=ywsz123
#-------Oracle--yujing-----#
jdbc.driverClassName2=oracle.jdbc.driver.OracleDriver
jdbc.url2=jdbc:oracle:thin:@10.35.50.215:1521:orcl
jdbc.username2=ywsz
jdbc.password2=ywsz


#-------MySQL-------#
jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc\:mysql\://127.0.0.1\:3306/csaqys?autoReconnect\=true&characterEncoding\=UTF-8
#jdbc.url=jdbc\:mysql\://50.64.130.123\:3306/csaqys?autoReconnect\=true&characterEncoding\=UTF-8
#jdbc.url=jdbc\:mysql\://50.64.130.123\:3306/csaqys-test?autoReconnect\=true&characterEncoding\=UTF-8
#-------DB2-------#
#jdbc.driverClassName=com.ibm.db2.jcc.DB2Driver
#jdbc.url=jdbc:db2://192.168.1.15:50000/ESERVER2




jdbc.url=jdbc\:mysql\://127.0.0.1\:3306/csaqys-test?autoReconnect\=true&characterEncoding\=UTF-8
jdbc.username=root
jdbc.password=123456



#jdbc.username=root
#jdbc.password=Szrj2021@root
#jdbc.password=jsywsz@root