#-------闂佸搫鍊稿ú锝呪枎閵忥紕鈻斿┑鐘辫兌閻愬﹪鏌涘鍐毎缂佹鎳忓顏堟偩鐏炲墽鏆犻柣鐘辫閸ㄦ壆娆㈤敓?-------#
uploadFile=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles
uploadFile_Pricture=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles\\pictures
uploadFile_Document=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles\\files
uploadFile_Audio=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles\\audio
layeditPricture=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles\\video
uploadFile_Sign=D\:\\Work\\Tomcat6.0\\Tomcat 6.0\\webapps\\JYRiskManage\\uploadFiles\\sign
#----闂備焦婢樼粔鍫曟偪閸℃瑥瀵查柤濮愬�閸╃娀鏌涘顒傂ょ悮?